---
title: "R Notebook_Alister_Project"
output: html_notebook
---

```{r}
#Importing Alberta.csv 
data = read.csv("C:/Users/alist/OneDrive/Desktop/Data 606/Project/chess_df_overall.csv", header=TRUE)
head(data,3)
```

```{r}
df2<-data[!(data$winner=="DRAW"),]
df2
```
```{r}
unique(df2$winner)
```
```{r}
#write.csv(df2 , "C:/Users/alist/OneDrive/Desktop/Data 606/Project/chess_df_draw_dropped.csv", row.names=TRUE)
```

```{r}
#Q -Q plot Normality test
df2.white<-subset(df2,winner =="WHITE")
df2.black<-subset(df2,winner =="BLACK")
```
```{r}
variable_1<-c("turns","Rating_WB")
par(mfrow = c(2,1))

for(i in variable_1) {
  qqnorm(df2.white[[i]]);qqline(df2.white[[i]])}
```

<<<<<<< HEAD
>Normality test for Winnergroup using Shapiro Test
=======
>Normality test for Winner group using Shapiro Test
>>>>>>> 8c4e2163bed9cea32f462be51ea9bf2e6da91005

```{r}
shapiro.test(df2.white$turns[0:5000])
shapiro.test(df2.white$Rating_WB[0:5000])
```
```{r}
library(nortest)
ad.test(df2.white$turns)
ad.test(df2.white$Rating_WB)
```
> Passes the normality test


```{r}
par(mfrow = c(2,1))
for(i in variable_1) {
  qqnorm(df2.black[[i]]);qqline(df2.black[[i]])}
```
```{r}
shapiro.test(df2.black$turns[0:5000])
shapiro.test(df2.black$Rating_WB[0:5000])
```
```{r}
library(nortest)
ad.test(df2.black$turns)
ad.test(df2.black$Rating_WB)
```

> Variance test

```{r}
df2.sub = subset(df2,select = c(turns,Rating_WB))
df2.sub
```

```{r}
library(ggplot2)
library(GGally)
ggpairs(df2.sub,lower = list(continuous = "smooth_loess",combo ="facethist",discrete = "facetbar",na ="na"))
```


>Pending to check independence




********************************************
# Q2
> Reading the file for second question: 

```{r}
#File for second question
data_Q2 = read.csv("C:/Users/alist/OneDrive/Desktop/Data 606/Project/data-606-project/chess_strat_Q2.csv", header=TRUE)
head(data_Q2,3)
```

```{r}
unique(data_Q2$victory_status)
```
```{r}
#Q -Q plot Normality test
Q2.outoftime<-subset(data_Q2,victory_status =="OUTOFTIME")
Q2.resign<-subset(data_Q2,victory_status =="RESIGN")
Q2.mate<-subset(data_Q2,victory_status =="MATE")
```
```{r}
variable_2<-c("turns","Rating_WB")
par(mfrow = c(2,1))

for(i in variable_2) {
  qqnorm(Q2.outoftime[[i]]);qqline(Q2.outoftime[[i]])}
```
```{r}
shapiro.test(Q2.outoftime$turns[0:5000])
shapiro.test(Q2.outoftime$Rating_WB[0:5000])
```
```{r}
library(nortest)
ad.test(Q2.outoftime$turns)
ad.test(Q2.outoftime$Rating_WB)
```

```{r}
par(mfrow = c(2,1))
for(i in variable_2) {
  qqnorm(Q2.resign[[i]]);qqline(Q2.resign[[i]])}
```
```{r}
shapiro.test(Q2.resign$turns[0:5000])
shapiro.test(Q2.resign$Rating_WB[0:5000])
```
```{r}
library(nortest)
ad.test(Q2.resign$turns)
ad.test(Q2.resign$Rating_WB)
```
```{r}
par(mfrow = c(2,1))
for(i in variable_2) {
  qqnorm(Q2.mate[[i]]);qqline(Q2.mate[[i]])}
```
```{r}
shapiro.test(Q2.mate$turns[0:5000])
shapiro.test(Q2.mate$Rating_WB[0:5000])
```
```{r}
library(nortest)
ad.test(Q2.mate$turns)
ad.test(Q2.mate$Rating_WB)
```
>Variance Test for Q2

```{r}
Q2.sub = subset(data_Q2,select = c(turns,Rating_WB))
Q2.sub
```
```{r}
library(ggplot2)
library(GGally)
ggpairs(Q2.sub,lower = list(continuous = "smooth_loess",combo ="facethist",discrete = "facetbar",na ="na"))
```
