---
title: "R Notebook"
output: html_notebook
---

#Q2. What predictors are most important in telling how a game ends - using LDA, QDA, Multinomial - Chi-square test

```{r}
chess_data = read.csv("q2_stratified_imad_data.csv", header = TRUE)
chess_data
```

```{r}
lda.fit<-lda(victory_status~., data=chess_data)
lda.fit
```

```{r}
plot(lda.fit)
```


```{r}
#predict with test
# lda.pred=predict(lda.fit, Test)
# names(lda.pred)
```

```{r}
#table(lda.pred$class, Test$victory_status)
```

```{r}
library(klaR)
partimat(victory_status~., data = chess_data, method="lda")
```

#cross validation
```{r}
library(caret)
```
```{r}
set.seed(1)
folds<-createFolds(chess_data$victory_status, k=10)
```


```{r}
fold1<-chess_data[folds$Fold1,]
table(fold1$victory_status)
```
#wrote a function to calculate the misclassification rate (LDA).
```{r}
library (MASS)
misclassification<-function(idx){
train<-chess_data[-idx,]
test<-chess_data[idx,]
fit<-lda(victory_status~., data=train)
pred<-predict(fit,test,type = "class")
return(1-mean(pred$class==test$victory_status))
}
```
#apply the function “lapply” to pass along a vector of indices to the function “misclassification”
```{r}
mis_rate=lapply(folds,misclassification)
mis_rate
```
#calculate the average misclassification error.
```{r}
mean(as.numeric(mis_rate))
```